# Tauschbörse & Album: zwei Konten tauschen Samen, Erfolge und Titel.
# Aufruf: python3 tests/trade_e2e.py <URL> <Screenshot-Ordner>   (lokal mit frischem node tests/devserver.mjs 8130)
import sys, time
from playwright.sync_api import sync_playwright
URL = sys.argv[1].rstrip('/'); OUT = sys.argv[2].rstrip('/') + '/'
ARGS = ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist']
res = []
def check(n, ok, d=''):
    res.append(bool(ok)); print(('OK   ' if ok else 'FEHL ') + n + (f'  [{d}]' if d else ''))
def register(pg, name, email):
    pg.goto(URL + '/?debug=1&notut=1')
    pg.wait_for_selector('#authBox:not([hidden])', timeout=180000)
    pg.locator('#authBox [data-tab=register]').click()
    pg.fill('#registerForm [name=name]', name); pg.fill('#registerForm [name=email]', email); pg.fill('#registerForm [name=password]', 'blumen123')
    pg.check('#registerForm [name=privacy]'); pg.locator('#registerForm button[type=submit]').click()
    pg.wait_for_function('window.BW && document.getElementById("loader").hidden', timeout=90000); pg.wait_for_timeout(800)
    pg.evaluate('BW.G.markIntroSeen(BW.state); BW.state.tutorialDone = 1; BW.ui.modalQueue.length = 0; BW.ui.closeModal()')
def sync(pg): pg.evaluate('BW.hub.tick()'); pg.wait_for_timeout(1200)
st = str(int(time.time()))[-5:]
with sync_playwright() as p:
    b = p.chromium.launch(args=ARGS)
    A = b.new_context(viewport={'width': 390, 'height': 844}, is_mobile=True, has_touch=True, bypass_csp=True).new_page()
    B = b.new_context(viewport={'width': 390, 'height': 844}, is_mobile=True, has_touch=True, bypass_csp=True).new_page()
    errs = []; A.on('pageerror', lambda e: errs.append('A ' + str(e))); B.on('pageerror', lambda e: errs.append('B ' + str(e)))
    register(A, 'Dora' + st, f'dora{st}@example.com')
    A.evaluate("BW.ui.nav('settings')")  # 3D pausiert, damit das zweite Fenster schnell lädt
    register(B, 'Emil' + st, f'emil{st}@example.com')
    B.evaluate("BW.ui.nav('settings')")
    # Samen per Debug geben
    A.evaluate("BW.G.addSeeds(BW.state, { marigold: 3, crocus: 2 }); BW.actions.afterTrade()")
    B.evaluate("BW.G.addSeeds(BW.state, { heartRose: 2 }); BW.actions.afterTrade()")
    A.evaluate("BW.ui.nav('friends')"); A.wait_for_timeout(600)
    check('Tauschbörse-Karte bei Freunden', A.locator('[data-act=openTrade]').count() == 1)
    A.locator('[data-act=openTrade]').click(); A.wait_for_timeout(1500)
    check('Tauschbörse offen, Samenbeutel zeigt 3× Tagetes', A.evaluate('BW.ui.panel') == 'trade' and '3×' in A.locator('.seedbag').inner_text())
    A.screenshot(path=OUT + 'trade_1.png')
    A.select_option('form[data-form=tradeOffer] [name=give]', 'marigold'); A.fill('form[data-form=tradeOffer] [name=giveN]', '2')
    A.select_option('form[data-form=tradeOffer] [name=want]', 'heartRose'); A.fill('form[data-form=tradeOffer] [name=wantN]', '1')
    A.locator('form[data-form=tradeOffer] button[type=submit]').click(); A.wait_for_timeout(2000)
    check('Angebot eingestellt, Samen reserviert', A.evaluate("BW.G.seedCount(BW.state, 'marigold')") == 1 and A.locator('.card.trade.mine').count() == 1)
    A.screenshot(path=OUT + 'trade_2.png')
    B.evaluate("BW.ui.nav('trade')"); B.wait_for_timeout(2000)
    check('Emil sieht Doras Angebot', B.locator('.card.trade').count() >= 1 and 'Dora' in B.locator('.card.trade').first.inner_text())
    B.locator('.card.trade [data-act=tradeAccept]').first.click(); B.wait_for_timeout(2500)
    check('Emil hat getauscht: 2 Tagetes, 1 Herzrose', B.evaluate("BW.G.seedCount(BW.state, 'marigold')") == 2 and B.evaluate("BW.G.seedCount(BW.state, 'heartRose')") == 1)
    B.screenshot(path=OUT + 'trade_3.png')
    sync(A); A.wait_for_timeout(1500)
    check('Dora bekam 1 Herzrose-Samen per Inbox', A.evaluate("BW.G.seedCount(BW.state, 'heartRose')") == 1 and A.evaluate('BW.state.stats.trades') == 1)
    # Angebot zurückziehen
    A.evaluate("BW.ui.nav('trade')"); A.wait_for_timeout(1200)
    A.select_option('form[data-form=tradeOffer] [name=give]', 'crocus'); A.select_option('form[data-form=tradeOffer] [name=want]', 'lilac')
    A.locator('form[data-form=tradeOffer] button[type=submit]').click(); A.wait_for_timeout(2000)
    A.locator('.card.trade.mine [data-act=tradeCancel]').first.click(); A.wait_for_timeout(2000)
    check('Angebot zurückgezogen, Samen zurück', A.evaluate("BW.G.seedCount(BW.state, 'crocus')") == 2 and A.locator('.card.trade.mine').count() == 0)
    # Samen schenken (Freunde)
    A.evaluate(f"BW.hub.act('request', 'Emil{st}')"); A.wait_for_timeout(1200); sync(B)
    B.evaluate(f"BW.hub.act('accept', BW.hub.data.incoming[0].id)"); B.wait_for_timeout(1200); sync(A)
    A.evaluate("BW.ui.nav('friends')"); A.wait_for_timeout(800)
    A.locator('[data-act=giftMenu]').first.click(); A.wait_for_timeout(600)
    check('Geschenk-Dialog zeigt Samen', A.locator('[data-act=sendSeeds]').count() >= 1)
    A.screenshot(path=OUT + 'trade_4.png')
    A.locator('[data-act=sendSeeds][data-seed=crocus]').click(); A.wait_for_timeout(2000)
    check('Samen verschenkt', A.evaluate("BW.G.seedCount(BW.state, 'crocus')") == 1)
    sync(B); B.wait_for_timeout(1500)
    check('Emil hat den Krokus-Samen bekommen', B.evaluate("BW.G.seedCount(BW.state, 'crocus')") == 1)
    # Nach dem Event mit Samen säen: Krokus (Frühling) ist im Oktober nur mit Samen säbar
    B.evaluate("BW.ui.closeModal(); BW.ui.nav('garden'); BW.actions.tapBed(0)"); B.wait_for_timeout(800)
    check('Krokus-Samen in der Saat-Auswahl', B.locator('#sheet .seed[data-id=crocus]').count() == 1 and 'Samen' in B.locator('#sheet .seed[data-id=crocus]').inner_text())
    B.screenshot(path=OUT + 'trade_5.png')
    B.locator('#sheet .seed[data-id=crocus]').click(); B.wait_for_timeout(800)
    check('Krokus gesät, Samen verbraucht', B.evaluate("BW.state.beds[0].seed") == 'crocus' and B.evaluate("BW.G.seedCount(BW.state, 'crocus')") == 0)
    # Album
    B.evaluate("for (const k of BW.ui.icons && Object.keys(BW.state.collection).length < 10 ? ['daisy','tulip','cornflower','sunflower','lavender','rose','poppy','orchid','lily','hydrangea'] : []) BW.state.collection[k] = { count: 1, shiny: 0 }; BW.actions.afterTrade()")
    B.wait_for_timeout(2500)
    check('Erfolg „Erste Blüten“ erreicht + Dialog', 'disc10' in B.evaluate('BW.state.achievements') and 'Erfolg' in B.locator('#modal').inner_text())
    B.screenshot(path=OUT + 'album_1.png')
    B.evaluate("BW.ui.modalQueue.length = 0; BW.ui.closeModal(); BW.ui.nav('collection', 'album')"); B.wait_for_timeout(800)
    check('Album-Tab mit Erfolgen', B.locator('.card.ach').count() >= 10 and B.locator('.card.ach.done').count() == 1)
    B.screenshot(path=OUT + 'album_2.png')
    B.evaluate("for (const k of Object.keys(BW.C ? BW.C.SEEDS : {})) {}")
    B.evaluate("BW.state.collection = Object.fromEntries(['daisy','tulip','cornflower','sunflower','lavender','rose','poppy','orchid','lily','hydrangea','dahlia','peony','magnolia','moonflower','rainbowTulip','sunTulip','skyCornflower','goldRose','firePoppy','moonOrchid'].map(k => [k, {count:1, shiny:0}])); BW.actions.afterTrade()"); B.wait_for_timeout(2500)
    check('Titel „Sammler“ erhalten', 'sammler' in B.evaluate('BW.state.titles') and B.evaluate('BW.state.title') == 'sammler')
    B.evaluate("BW.ui.modalQueue.length = 0; BW.ui.closeModal(); BW.ui.nav('collection', 'album')"); B.wait_for_timeout(600)
    check('Titel-Auswahl sichtbar', B.locator('.titles .tag').count() >= 2)
    B.locator('.titles .tag[data-id=""]').click(); B.wait_for_timeout(500)
    check('Titel abgelegt', B.evaluate('BW.state.title') == '')
    B.locator('.titles .tag[data-id=sammler]').click(); B.wait_for_timeout(500)
    B.evaluate('BW.cloud.dirty = true; BW.cloud.flush()'); B.wait_for_timeout(2500); sync(A); A.evaluate("BW.ui.nav('friends')"); A.wait_for_timeout(800)
    check('Titel in Doras Freundesliste', 'Sammler' in A.locator('.card.friend').first.inner_text())
    A.screenshot(path=OUT + 'album_3.png')
    check('Kein JS-Fehler', not errs, '; '.join(errs)[:300])
    b.close()
print(f'{sum(res)}/{len(res)} bestanden')
sys.exit(0 if all(res) else 1)
